### ISSUE TITLE
columns in output of calculate_ani_distances_p.py

### ISSUE THREAD

**Issue by graceblackwell** [santirdnd/pTU_paper#2]
Hi, 

I was wondering what the different columns in the output file of the calculate_ani_distances_p.py script? Particularly from min_hits on? Also which column was used to calculate the edge distances for genome_similarity_nerwork.py in the manuscript?

Thanks for your help, 
Grace

**Comment by santirdnd** [comment]
Hello Grace,

calculate_ani_distances_p.py is just a wrapper of ani.rb to parallelize ANI calculation. When comparing 2 genomes, ani.rb slices both genomes using a sliding window algorithm and uses blastn to find all homologous/orthologous fragments. Homologs are the best hits (minimum 70% id and %70 coverage) when blasting the query genome fragments against the reference ones (One-way ANI 1 in ani.rb output) or viceversa (One-way ANI 2). Orthologs are the best reciprocal hits (Two-way ANI). Finally, to yield the ANI value, the script averages the percentage identity of all homologous/orthologous fragments. Our preference is using the Two-way ANI values (orthologs).

There is a final catch, there must be a minimum number of fragments for ANI to be valid, otherwise 0 is assigned. This is to avoid getting a high ANI when 2 different genomes share, for example, only an IS. As this threshold we use the number of fragments necessary to cover at least 50% of the shortest genome while taking into account that fragments can overlap (because having used a sliding window algorithm to create the fragments). For details look at lines 131-135 of calculate_ani_distances_p.py or equations 1 and 2 of the paper.

Regarding the columns descriptions:
- Columns 1 and 2: Query and reference genome labels (taken from the filename)
- Columns 3 and 4: Query and reference genome sizes (in base pairs)
- Column 5 (min_hits): Minimum number of fragments needed to cover 50% of the shortest genome (either the query or the reference genome)
- Column 6 (ANI_o1): Mean %id of all homologous fragments found using "One-way ANI 1" calculation mode
- Column 7 (ANI_o1_SD): Standard dev of %id of all homologous fragments for "One-way ANI 1"
- Column 8 (ANI_o1_frag): Number of homologous fragments found using "One-way ANI 1"
- Coulmns 9, 10 and 11: These are the "One-way ANI 2" equivalents of columns 6, 7 and 8
- Coulmns 12, 13 and 14: These are the "Two-way ANI" equivalents of columns 6, 7 and 8

I hope this helps. Best regards,
    Santiago

**Comment by graceblackwell** [comment]
Hi Santiago,

Thanks very much for your detailed response, it has clarified a lot of things for me!

Thanks, 
Grace

**Comment by santirdnd** [comment]
You're welcome
